### ISSUE TITLE
Crash on "Write MD-UV380 user database to radio"

### ISSUE THREAD

**Issue by fred777** [DaleFarnsworth-DMR/editcp#20]
When I hit "Write MD-UV380 user database to radio", editcp will just crash. After restart it will show the following error:
```
panic: runtime error: slice bounds out of range [1:0]

goroutine 24 [running]:
github.com/dalefarnsworth-dmr/userdb.downloadReflectorUsers(0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/dalefarnsworth-dmr/userdb@v1.0.26/userdb.go:1112 +0x373
github.com/dalefarnsworth-dmr/userdb.do(0x2, 0x195885c, 0x14c3a200)
	github.com/dalefarnsworth-dmr/userdb@v1.0.26/userdb.go:1189 +0x30
created by github.com/dalefarnsworth-dmr/userdb.(*UsersDB).getUsers
	github.com/dalefarnsworth-dmr/userdb@v1.0.26/userdb.go:1199 +0x8a
```

My RT3S/MD-UV380 has latest firmware RT3S(CSV-GPS)-P18.16.bin

Not sure if I am supposed to download the user database somehow first... I'm a DMR newbee...

**Comment by DaleFarnsworth** [comment]
Thanks.  I ran into that issue, but think it should not occur with recent versions of editcp, but I could be wrong.  What version of editcp are you using?

**Comment by fred777** [comment]
It happens on both - Linux and Windows - with version 1.0.28

I tried also with dmrconfig: https://github.com/OpenRTX/dmrconfig

It seems the radio drops connection and reboots when initiating the upload. (I'm using a stripped down database with only 14000 contacts but it also happens with full database (which is too big for the memory)).

Side note: In the device, the ContactsCSV list was always showing garbage - right from the start after the firmware update and before any attempt to upload the db. There where 65536 items in the list with random non-asci characters.

I finally got the db transferred with the original tool from Retevis on Windows.

Since then, it has become possible to upload the db with editcp without any issues.

So I guess it's an issue with the internal memory state of the radio.

**Comment by DaleFarnsworth** [comment]
I'm pretty sure it's a bug in editcp.  It occurs when one of the user database files it downloads has a zero length. I'll look into it.  Thanks for the report.  BTW, the maximum number of user contacts that the MD-UV380 can hold is 122197 users.

**Comment by DaleFarnsworth** [comment]
Please try editcp v1.0.29

Thanks.

Dale NO7K
